from django.urls import path
from .views import *

urlpatterns = [
    path('suivi', suivi, name='suivi'),
    path('liste_dossiers/', liste_dossiers, name='liste_dossiers'),
    path('liste_prescriptions/', liste_prescriptions, name='liste_prescriptions'),
    path('suspect/<int:id>', suspect, name='suspect'),
    path('contamines/<int:id>', contamines, name='contamines'),
    path('test_negatif/<int:id>', test_negatif, name='test_negatif'),
    path('test_positif/<int:id>', test_positif, name='test_positif'),
    path('deces/<int:id>', deces, name='deces'),
    path('gueri/<int:id>', gueri, name='gueri'),
    path('rendez_vous/', rendez_vous, name='rendez_vous'),
    path('update_rdv/<int:id>', update_rdv, name='update_rdv'),
    path('annuler_rdv/<int:id>', annuler_rdv, name='annuler_rdv'),
    path('effectuer_rdv/<int:id>', effectuer_rdv, name='effectuer_rdv'),
    path('consultation/', consultation, name='consultation'),
    path('antecedent/', antecedent, name='antecedent'),
    path('prescription/', prescription, name='prescription'),
    path('hospitalisation/', hospitalisation, name='hospitalisation'),
    path('update_hosp/<int:id>', update_hosp, name='update_hosp'),
    path('terminer_hosp/<int:id>', terminer_hosp, name='terminer_hosp'),
    path('compte_medecin/', compte, name='compte_medecin'),
    path('update_compte/<int:id>', update_compte, name='update_compte_medecin'),
    path('dossiers/', liste_dossiers, name='liste_dossiers'),
    path('cloturer-dossier/<int:id>/', cloturer_dossier, name='cloturer_dossier'),
    path('prescriptions/', liste_prescriptions, name='liste_prescriptions'),
    path('nouvelle-prescription/', nouvelle_prescription, name='nouvelle_prescription'),
]
