# Generated by Django 4.2.3 on 2023-07-16 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Receptionniste', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rendez_vous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(max_length=50)),
                ('date_rdv', models.DateField()),
                ('statut', models.CharField(default='en cours', max_length=50)),
                ('id_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Receptionniste.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicament', models.CharField(max_length=50)),
                ('quantite', models.IntegerField()),
                ('posologie', models.CharField(max_length=50)),
                ('id_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Receptionniste.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Hospitalisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(max_length=50)),
                ('date_ent', models.DateField()),
                ('date_sort', models.DateField()),
                ('statut', models.CharField(default='en cours', max_length=50)),
                ('id_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Receptionniste.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.IntegerField()),
                ('sat_oxyg', models.IntegerField()),
                ('freq_resp', models.IntegerField()),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('id_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Receptionniste.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Antecedent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('id_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Receptionniste.patient')),
            ],
        ),
    ]
